FROM python:3.10

RUN echo '[global]\nindex-url=https://mirrors.aliyun.com/pypi/simple/\n' >> /etc/pip.conf

ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt /root/requirements.txt
WORKDIR /root
RUN pip install --no-cache-dir -r /root/requirements.txt

COPY ./code /root/code

WORKDIR /root/code/demo
CMD ["python", "generateUI.py", "--apiurl", "http://api-service:54224/generate"]
