apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  type: NodePort
  selector:
    app: gradio
  ports:
    - name: gradio-port
      protocol: TCP
      port: 7860
      targetPort: 7860